/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.nio.channels.Selector;

public class App {

  public static void main(String[] args) {

    try {
      ControllersLoader controllersLoader = new ControllersLoader();

      controllersLoader.loadControllers();

      Selector selector = Selector.open();
      HttpRequestParser httpRequestParser = new HttpRequestParser();

      HttpResponseBuilder httpResponseBuilder = new HttpResponseBuilder();

      RequestHandler requestHandler = new RequestHandler(httpResponseBuilder);

      TCPServer tcpServer = new TCPServer(selector, httpRequestParser, requestHandler);

      tcpServer.startServer();

    } catch (Exception e) {
      e.printStackTrace();
    }
  }
}
